device: cpu
env:
  arrival_model: poisson
  cloud_compute_mips: 5000.0
  deadline_range:
  - 5
  - 20
  edge_compute_mips: 2000.0
  emax_range:
  - 0.05
  - 0.3
  energy_coeff_compute: 2.0e-11
  energy_coeff_tx: 1.0e-09
  horizon_steps: 600
  include_cloud: true
  link_fair_share: true
  max_tasks_per_vehicle: 10
  max_vehicles: 50
  noise_dbm: -95.0
  num_edges: 8
  power_bins: 1
  power_rule: distance
  priority_levels: 4
  task_arrival_lambda: 1.3
  task_arrival_rate: 1.0
  task_burst_max: 5
  task_cycles:
  - 2.0e9
  - 20.0e9
  task_queue_capacity: 128
  task_size_bits:
  - 2.0e6
  - 20.0e6
  top_k: 4
  tx_power_dbm_bins:
  - 1
  v2i_bandwidth_mhz: 100.0
  v2v_bandwidth_mhz: 20.0
  vehicle_compute_mips: 1000.0
  w_distance: 0.5
  w_workload: 0.5
ppo:
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.01
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 4
  n_steps: 2048
  total_timesteps: 200000
  vf_coef: 0.5
reward:
  lambda_deadline: 5.0
  lambda_energy: 1.0
  lambda_time: 1.0
seed: 42
