seed: 42
device: cpu

env:
  horizon_steps: 600
  max_vehicles: 50
  num_edges: 8
  include_cloud: true
  top_k: 4
  priority_levels: 4            # configurable
  power_bins: 5                 # configurable
  power_rule: "bins"            # "bins" | "distance"
  max_tasks_per_vehicle: 10
  task_queue_capacity: 128

  # --- placeholders: replace with Table III values ---
  v2v_bandwidth_mhz: 10.0
  v2i_bandwidth_mhz: 20.0
  noise_dbm: -90.0
  tx_power_dbm_bins: [-5, 0, 5, 10, 15]
  vehicle_compute_mips: 50.0
  edge_compute_mips: 500.0
  cloud_compute_mips: 2000.0
  energy_coeff_tx: 1.0e-6
  energy_coeff_compute: 1.0e-9
  link_fair_share: true

  task_arrival_rate: 0.8
  task_size_bits: [1.0e6, 4.0e6]
  task_cycles: [5.0e7, 2.0e8]
  deadline_range: [50, 200]
  emax_range: [0.05, 0.3]

  w_distance: 0.5
  w_workload: 0.5

reward:
  lambda_time: 1.0
  lambda_energy: 1.0
  lambda_deadline: 5.0

ppo:
  total_timesteps: 200000
  n_steps: 2048
  batch_size: 512
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  learning_rate: 0.0003
